function init(self)
    msg.post(".", "acquire_input_focus")
    -- Play victory sound
    sound.play("/win#victory_sound")
end

function on_input(self, action_id, action)
    if action_id == hash("touch") and action.pressed then
        local restart_button = gui.get_node("restart_button")
        if gui.pick_node(restart_button, action.x, action.y) then
            msg.post("main:/loader#loader_script", "restart_game")
        end
    end
end
